services:
  backend:
    build:
      context: .
      dockerfile: MISA.SaleOrder.Fresher.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__conn=Server=db;Port=3306;Database=sale;User=root;Password=12345678;
    depends_on:
      - db
    networks:
      - salesnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"] 
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: sale
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  #
    networks:
      - salesnet

volumes:
  mysql_data:

networks:
  salesnet:
